// ============================================================
// Exam Rescue — Class 10 Social Science Syllabus (CBSE/NCERT)
// ============================================================

import { Chapter, Topic, Subject } from '@/types';

export const socialSubject: Subject = {
  id: 'social_science',
  classLevelId: 10,
  name: 'Social Science',
  icon: '🌍',
  color: '#f59e0b',
};

export const socialChapters: Chapter[] = [
  // History
  {
    id: 'ss-hist-ch1',
    subjectId: 'social_science',
    chapterNumber: 1,
    name: 'The Rise of Nationalism in Europe',
    description: 'French Revolution, nation-state, liberalism, revolution of 1830 and 1848',
    topicCount: 5,
  },
  {
    id: 'ss-hist-ch2',
    subjectId: 'social_science',
    chapterNumber: 2,
    name: 'Nationalism in India',
    description: 'Anti-colonial movements, non-cooperation, civil disobedience, Quit India',
    topicCount: 5,
  },
  {
    id: 'ss-hist-ch3',
    subjectId: 'social_science',
    chapterNumber: 3,
    name: 'The Making of a Global World',
    description: 'Globalization, trade, migration, pre-modern world, 19th century',
    topicCount: 5,
  },
  {
    id: 'ss-hist-ch4',
    subjectId: 'social_science',
    chapterNumber: 4,
    name: 'The Age of Industrialisation',
    description: 'Industrial revolution, proto-industrialization, factory system, workers',
    topicCount: 5,
  },
  {
    id: 'ss-hist-ch5',
    subjectId: 'social_science',
    chapterNumber: 5,
    name: 'Print Culture and the Modern World',
    description: 'Print revolution, censorship, print and dissent, new publications',
    topicCount: 4,
  },
  // Geography
  {
    id: 'ss-geo-ch1',
    subjectId: 'social_science',
    chapterNumber: 6,
    name: 'Resources and Development',
    description: 'Types of resources, resource planning, land use, soil erosion',
    topicCount: 5,
  },
  {
    id: 'ss-geo-ch2',
    subjectId: 'social_science',
    chapterNumber: 7,
    name: 'Forest and Wildlife Resources',
    description: 'Conservation, biodiversity, protected areas, community reserves',
    topicCount: 4,
  },
  {
    id: 'ss-geo-ch3',
    subjectId: 'social_science',
    chapterNumber: 8,
    name: 'Water Resources',
    description: 'Water conservation, rainwater harvesting, dams, water scarcity',
    topicCount: 4,
  },
  {
    id: 'ss-geo-ch4',
    subjectId: 'social_science',
    chapterNumber: 9,
    name: 'Agriculture',
    description: 'Types of farming, crops, Green Revolution, food security',
    topicCount: 5,
  },
  {
    id: 'ss-geo-ch5',
    subjectId: 'social_science',
    chapterNumber: 10,
    name: 'Minerals and Energy Resources',
    description: 'Mineral types, distribution, conservation, conventional and non-conventional energy',
    topicCount: 4,
  },
  {
    id: 'ss-geo-ch6',
    subjectId: 'social_science',
    chapterNumber: 11,
    name: 'Manufacturing Industries',
    description: 'Industrial classification, location, pollution, industrial policy',
    topicCount: 4,
  },
  {
    id: 'ss-geo-ch7',
    subjectId: 'social_science',
    chapterNumber: 12,
    name: 'Lifelines of National Economy',
    description: 'Transport, communication, trade, WTO, globalization',
    topicCount: 4,
  },
  // Political Science
  {
    id: 'ss-ps-ch1',
    subjectId: 'social_science',
    chapterNumber: 13,
    name: 'Power Sharing',
    description: 'Belgium and Sri Lanka models, forms of power sharing, federalism',
    topicCount: 4,
  },
  {
    id: 'ss-ps-ch2',
    subjectId: 'social_science',
    chapterNumber: 14,
    name: 'Federalism',
    description: 'Federal system, center-state relations, decentralization, panchayati raj',
    topicCount: 4,
  },
  {
    id: 'ss-ps-ch3',
    subjectId: 'social_science',
    chapterNumber: 15,
    name: 'Democracy and Diversity',
    description: 'Social differences, political competition, accommodation, integration',
    topicCount: 3,
  },
  {
    id: 'ss-ps-ch4',
    subjectId: 'social_science',
    chapterNumber: 16,
    name: 'Gender, Religion and Caste',
    description: 'Gender and politics, communalism, casteism, secularism',
    topicCount: 4,
  },
  {
    id: 'ss-ps-ch5',
    subjectId: 'social_science',
    chapterNumber: 17,
    name: 'Political Parties',
    description: 'Functions, types, challenges, party system in India',
    topicCount: 4,
  },
  {
    id: 'ss-ps-ch6',
    subjectId: 'social_science',
    chapterNumber: 18,
    name: 'Outcomes of Democracy',
    description: 'Accountability, responsiveness, corruption, transparency',
    topicCount: 3,
  },
  // Economics
  {
    id: 'ss-eco-ch1',
    subjectId: 'social_science',
    chapterNumber: 19,
    name: 'Development',
    description: 'Per capita income, HDI, sustainability, income and other criteria',
    topicCount: 4,
  },
  {
    id: 'ss-eco-ch2',
    subjectId: 'social_science',
    chapterNumber: 20,
    name: 'Sectors of the Indian Economy',
    description: 'Primary, secondary, tertiary sectors, organized and unorganized, employment',
    topicCount: 5,
  },
  {
    id: 'ss-eco-ch3',
    subjectId: 'social_science',
    chapterNumber: 21,
    name: 'Money and Credit',
    description: 'Money as medium of exchange, credit, formal and informal sources, RBI',
    topicCount: 4,
  },
  {
    id: 'ss-eco-ch4',
    subjectId: 'social_science',
    chapterNumber: 22,
    name: 'Globalisation and the Indian Economy',
    description: 'Liberalization, privatization, globalisation, WTO, trade barriers',
    topicCount: 4,
  },
  {
    id: 'ss-eco-ch5',
    subjectId: 'social_science',
    chapterNumber: 23,
    name: 'Consumer Rights',
    description: 'Consumer protection, RTI, consumer forums, awareness',
    topicCount: 3,
  },
];

export const socialTopics: Record<string, Topic[]> = {
  'ss-hist-ch1': [
    { id: 'ss-hist-ch1-t1', chapterId: 'ss-hist-ch1', name: 'French Revolution and Nationalism', importance: 8, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-hist-ch1-t2', chapterId: 'ss-hist-ch1', name: 'Nation-State and Liberty', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch1-t3', chapterId: 'ss-hist-ch1', name: 'Revolution of 1830 and 1848', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch1-t4', chapterId: 'ss-hist-ch1', name: 'Unification of Germany and Italy', importance: 8, difficulty: 6, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-hist-ch1-t5', chapterId: 'ss-hist-ch1', name: 'Alphabetical Revolution — Giuseppe Mazzini', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-hist-ch2': [
    { id: 'ss-hist-ch2-t1', chapterId: 'ss-hist-ch2', name: 'First World War and Satyagraha', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch2-t2', chapterId: 'ss-hist-ch2', name: 'Non-Cooperation Movement', importance: 9, difficulty: 5, estimatedMinutes: 45, isHighYield: true },
    { id: 'ss-hist-ch2-t3', chapterId: 'ss-hist-ch2', name: 'Civil Disobedience Movement', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'ss-hist-ch2-t4', chapterId: 'ss-hist-ch2', name: 'Quit India Movement', importance: 8, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch2-t5', chapterId: 'ss-hist-ch2', name: 'Role of Different Social Groups', importance: 7, difficulty: 5, estimatedMinutes: 30 },
  ],
  'ss-hist-ch3': [
    { id: 'ss-hist-ch3-t1', chapterId: 'ss-hist-ch3', name: 'The Pre-Modern World', importance: 6, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-hist-ch3-t2', chapterId: 'ss-hist-ch3', name: '19th Century Global Economy', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch3-t3', chapterId: 'ss-hist-ch3', name: 'Interwar Economy and Great Depression', importance: 8, difficulty: 6, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-hist-ch3-t4', chapterId: 'ss-hist-ch3', name: 'Post-War Reconstruction and Bretton Woods', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch3-t5', chapterId: 'ss-hist-ch3', name: 'India and Globalization', importance: 7, difficulty: 5, estimatedMinutes: 30 },
  ],
  'ss-hist-ch4': [
    { id: 'ss-hist-ch4-t1', chapterId: 'ss-hist-ch4', name: 'Industrial Revolution in Britain', importance: 8, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-hist-ch4-t2', chapterId: 'ss-hist-ch4', name: 'Proto-Industrialization', importance: 6, difficulty: 5, estimatedMinutes: 30 },
    { id: 'ss-hist-ch4-t3', chapterId: 'ss-hist-ch4', name: 'Factory System and Workers', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch4-t4', chapterId: 'ss-hist-ch4', name: 'Industrialization in India', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-hist-ch4-t5', chapterId: 'ss-hist-ch4', name: 'Industrial Growth and Modern Industries', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-hist-ch5': [
    { id: 'ss-hist-ch5-t1', chapterId: 'ss-hist-ch5', name: 'Print Revolution in Europe', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-hist-ch5-t2', chapterId: 'ss-hist-ch5', name: 'Print in India', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-hist-ch5-t3', chapterId: 'ss-hist-ch5', name: 'Print and Social Reform', importance: 6, difficulty: 4, estimatedMinutes: 25 },
    { id: 'ss-hist-ch5-t4', chapterId: 'ss-hist-ch5', name: 'Censorship and Press', importance: 5, difficulty: 3, estimatedMinutes: 20 },
  ],
  'ss-geo-ch1': [
    { id: 'ss-geo-ch1-t1', chapterId: 'ss-geo-ch1', name: 'Types of Resources', importance: 7, difficulty: 3, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-geo-ch1-t2', chapterId: 'ss-geo-ch1', name: 'Resource Planning in India', importance: 8, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-geo-ch1-t3', chapterId: 'ss-geo-ch1', name: 'Land Use and Land Degradation', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch1-t4', chapterId: 'ss-geo-ch1', name: 'Soil Types and Conservation', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch1-t5', chapterId: 'ss-geo-ch1', name: 'Methods of Soil Conservation', importance: 6, difficulty: 3, estimatedMinutes: 25 },
  ],
  'ss-geo-ch2': [
    { id: 'ss-geo-ch2-t1', chapterId: 'ss-geo-ch2', name: 'Forest and Wildlife in India', importance: 6, difficulty: 3, estimatedMinutes: 25 },
    { id: 'ss-geo-ch2-t2', chapterId: 'ss-geo-ch2', name: 'Biodiversity and Conservation', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-geo-ch2-t3', chapterId: 'ss-geo-ch2', name: 'Protected Areas and Biosphere Reserves', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch2-t4', chapterId: 'ss-geo-ch2', name: 'Community Reserves and Conservation', importance: 6, difficulty: 3, estimatedMinutes: 25 },
  ],
  'ss-geo-ch3': [
    { id: 'ss-geo-ch3-t1', chapterId: 'ss-geo-ch3', name: 'Water Scarcity in India', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-geo-ch3-t2', chapterId: 'ss-geo-ch3', name: 'Rainwater Harvesting', importance: 8, difficulty: 4, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-geo-ch3-t3', chapterId: 'ss-geo-ch3', name: 'Dams and River Linking', importance: 6, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch3-t4', chapterId: 'ss-geo-ch3', name: 'Water Conservation Methods', importance: 7, difficulty: 3, estimatedMinutes: 25 },
  ],
  'ss-geo-ch4': [
    { id: 'ss-geo-ch4-t1', chapterId: 'ss-geo-ch4', name: 'Types of Farming', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-geo-ch4-t2', chapterId: 'ss-geo-ch4', name: 'Major Crops in India', importance: 8, difficulty: 4, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-geo-ch4-t3', chapterId: 'ss-geo-ch4', name: 'Green Revolution and Its Impacts', importance: 8, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-geo-ch4-t4', chapterId: 'ss-geo-ch4', name: 'Food Security and Public Distribution', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-geo-ch4-t5', chapterId: 'ss-geo-ch4', name: 'Limitations of Green Revolution', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-geo-ch5': [
    { id: 'ss-geo-ch5-t1', chapterId: 'ss-geo-ch5', name: 'Mineral Distribution in India', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch5-t2', chapterId: 'ss-geo-ch5', name: 'Energy Resources — Conventional', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-geo-ch5-t3', chapterId: 'ss-geo-ch5', name: 'Energy Resources — Non-Conventional', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-geo-ch5-t4', chapterId: 'ss-geo-ch5', name: 'Conservation of Minerals and Energy', importance: 6, difficulty: 3, estimatedMinutes: 25 },
  ],
  'ss-geo-ch6': [
    { id: 'ss-geo-ch6-t1', chapterId: 'ss-geo-ch6', name: 'Types of Industries', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch6-t2', chapterId: 'ss-geo-ch6', name: 'Location and Factors of Industrialization', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-geo-ch6-t3', chapterId: 'ss-geo-ch6', name: 'Industrial Pollution and Control', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-geo-ch6-t4', chapterId: 'ss-geo-ch6', name: 'National Manufacturing Policy', importance: 5, difficulty: 3, estimatedMinutes: 20 },
  ],
  'ss-geo-ch7': [
    { id: 'ss-geo-ch7-t1', chapterId: 'ss-geo-ch7', name: 'Transport Modes in India', importance: 6, difficulty: 3, estimatedMinutes: 25 },
    { id: 'ss-geo-ch7-t2', chapterId: 'ss-geo-ch7', name: 'Communication and IT', importance: 6, difficulty: 3, estimatedMinutes: 25 },
    { id: 'ss-geo-ch7-t3', chapterId: 'ss-geo-ch7', name: 'International Trade and WTO', importance: 7, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-geo-ch7-t4', chapterId: 'ss-geo-ch7', name: 'Globalization and Indian Economy', importance: 7, difficulty: 5, estimatedMinutes: 35 },
  ],
  'ss-ps-ch1': [
    { id: 'ss-ps-ch1-t1', chapterId: 'ss-ps-ch1', name: 'Power Sharing in Belgium', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-ps-ch1-t2', chapterId: 'ss-ps-ch1', name: 'Majoritarianism in Sri Lanka', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-ps-ch1-t3', chapterId: 'ss-ps-ch1', name: 'Forms of Power Sharing', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-ps-ch1-t4', chapterId: 'ss-ps-ch1', name: 'Why Power Sharing is Desirable', importance: 7, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-ps-ch2': [
    { id: 'ss-ps-ch2-t1', chapterId: 'ss-ps-ch2', name: 'Federal System — Features and Types', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-ps-ch2-t2', chapterId: 'ss-ps-ch2', name: 'Center-State Relations', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-ps-ch2-t3', chapterId: 'ss-ps-ch2', name: 'Decentralization and Panchayati Raj', importance: 7, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-ps-ch2-t4', chapterId: 'ss-ps-ch2', name: 'Indian Federal System — Challenges', importance: 6, difficulty: 5, estimatedMinutes: 30 },
  ],
  'ss-ps-ch3': [
    { id: 'ss-ps-ch3-t1', chapterId: 'ss-ps-ch3', name: 'Social Differences and Politics', importance: 6, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-ps-ch3-t2', chapterId: 'ss-ps-ch3', name: 'Political Competition and Accommodation', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-ps-ch3-t3', chapterId: 'ss-ps-ch3', name: 'Integration and National Unity', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-ps-ch4': [
    { id: 'ss-ps-ch4-t1', chapterId: 'ss-ps-ch4', name: 'Gender and Politics', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-ps-ch4-t2', chapterId: 'ss-ps-ch4', name: 'Communalism and Secularism', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-ps-ch4-t3', chapterId: 'ss-ps-ch4', name: 'Caste and Politics', importance: 7, difficulty: 5, estimatedMinutes: 30 },
    { id: 'ss-ps-ch4-t4', chapterId: 'ss-ps-ch4', name: 'Gender Issues in India', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-ps-ch5': [
    { id: 'ss-ps-ch5-t1', chapterId: 'ss-ps-ch5', name: 'Functions and Types of Political Parties', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-ps-ch5-t2', chapterId: 'ss-ps-ch5', name: 'National and Regional Parties', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-ps-ch5-t3', chapterId: 'ss-ps-ch5', name: 'Challenges Faced by Political Parties', importance: 6, difficulty: 4, estimatedMinutes: 25 },
    { id: 'ss-ps-ch5-t4', chapterId: 'ss-ps-ch5', name: 'Party System in India', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-ps-ch6': [
    { id: 'ss-ps-ch6-t1', chapterId: 'ss-ps-ch6', name: 'Accountability and Responsiveness', importance: 7, difficulty: 4, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-ps-ch6-t2', chapterId: 'ss-ps-ch6', name: 'Transparency and Corruption', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-ps-ch6-t3', chapterId: 'ss-ps-ch6', name: 'Outcomes — Strengths and Weaknesses', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-eco-ch1': [
    { id: 'ss-eco-ch1-t1', chapterId: 'ss-eco-ch1', name: 'Per Capita Income and Development', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-eco-ch1-t2', chapterId: 'ss-eco-ch1', name: 'Human Development Index', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-eco-ch1-t3', chapterId: 'ss-eco-ch1', name: 'Income and Other Criteria', importance: 6, difficulty: 4, estimatedMinutes: 25 },
    { id: 'ss-eco-ch1-t4', chapterId: 'ss-eco-ch1', name: 'Sustainability and Development', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-eco-ch2': [
    { id: 'ss-eco-ch2-t1', chapterId: 'ss-eco-ch2', name: 'Sectors of Economy — Primary, Secondary, Tertiary', importance: 8, difficulty: 4, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-eco-ch2-t2', chapterId: 'ss-eco-ch2', name: 'Organized and Unorganized Sectors', importance: 7, difficulty: 5, estimatedMinutes: 30 },
    { id: 'ss-eco-ch2-t3', chapterId: 'ss-eco-ch2', name: 'Employment and GDP', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-eco-ch2-t4', chapterId: 'ss-eco-ch2', name: 'Informalization and Jobless Growth', importance: 6, difficulty: 5, estimatedMinutes: 30 },
    { id: 'ss-eco-ch2-t5', chapterId: 'ss-eco-ch2', name: 'How to Create More Employment', importance: 7, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-eco-ch3': [
    { id: 'ss-eco-ch3-t1', chapterId: 'ss-eco-ch3', name: 'Money as Medium of Exchange', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'ss-eco-ch3-t2', chapterId: 'ss-eco-ch3', name: 'Credit and Its Types', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-eco-ch3-t3', chapterId: 'ss-eco-ch3', name: 'Formal and Informal Credit Sources', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-eco-ch3-t4', chapterId: 'ss-eco-ch3', name: 'RBI and Its Functions', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'ss-eco-ch4': [
    { id: 'ss-eco-ch4-t1', chapterId: 'ss-eco-ch4', name: 'Liberalization and Privatization', importance: 7, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'ss-eco-ch4-t2', chapterId: 'ss-eco-ch4', name: 'WTO and Trade Barriers', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'ss-eco-ch4-t3', chapterId: 'ss-eco-ch4', name: 'Globalisation and Its Impact on India', importance: 8, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'ss-eco-ch4-t4', chapterId: 'ss-eco-ch4', name: 'Fair Globalisation', importance: 5, difficulty: 4, estimatedMinutes: 20 },
  ],
  'ss-eco-ch5': [
    { id: 'ss-eco-ch5-t1', chapterId: 'ss-eco-ch5', name: 'Consumer Rights and Protection', importance: 7, difficulty: 3, estimatedMinutes: 30, isHighYield: true },
    { id: 'ss-eco-ch5-t2', chapterId: 'ss-eco-ch5', name: 'Consumer Forums and RTI', importance: 6, difficulty: 3, estimatedMinutes: 25 },
    { id: 'ss-eco-ch5-t3', chapterId: 'ss-eco-ch5', name: 'Consumer Awareness and Safety', importance: 6, difficulty: 3, estimatedMinutes: 25 },
  ],
};
