// ============================================================
// Exam Rescue — Class 10 Science Syllabus (CBSE/NCERT)
// ============================================================

import { Chapter, Topic, Subject } from '@/types';

export const scienceSubject: Subject = {
  id: 'science',
  classLevelId: 10,
  name: 'Science',
  icon: '🔬',
  color: '#10b981',
};

export const scienceChapters: Chapter[] = [
  {
    id: 'sci-ch1',
    subjectId: 'science',
    chapterNumber: 1,
    name: 'Chemical Reactions and Equations',
    description: 'Chemical reactions, equations, types of reactions, effects of oxidation reactions',
    topicCount: 6,
  },
  {
    id: 'sci-ch2',
    subjectId: 'science',
    chapterNumber: 2,
    name: 'Acids, Bases and Salts',
    description: 'Acids, bases, salts, pH scale, neutralization reactions',
    topicCount: 6,
  },
  {
    id: 'sci-ch3',
    subjectId: 'science',
    chapterNumber: 3,
    name: 'Metals and Non-metals',
    description: 'Properties of metals and non-metals, reactivity series, extraction of metals',
    topicCount: 6,
  },
  {
    id: 'sci-ch4',
    subjectId: 'science',
    chapterNumber: 4,
    name: 'Carbon and its Compounds',
    description: 'Carbon compounds, covalent bonding, functional groups, nomenclature',
    topicCount: 6,
  },
  {
    id: 'sci-ch5',
    subjectId: 'science',
    chapterNumber: 5,
    name: 'Life Processes',
    description: 'Nutrition, respiration, transportation, excretion in living organisms',
    topicCount: 6,
  },
  {
    id: 'sci-ch6',
    subjectId: 'science',
    chapterNumber: 6,
    name: 'Control and Coordination',
    description: 'Nervous system, endocrine system, coordination in plants',
    topicCount: 5,
  },
  {
    id: 'sci-ch7',
    subjectId: 'science',
    chapterNumber: 7,
    name: 'How do Organisms Reproduce?',
    description: 'Asexual and sexual reproduction, reproductive health',
    topicCount: 5,
  },
  {
    id: 'sci-ch8',
    subjectId: 'science',
    chapterNumber: 8,
    name: 'Heredity and Evolution',
    description: 'Heredity, Mendels laws, evolution, speciation',
    topicCount: 5,
  },
  {
    id: 'sci-ch9',
    subjectId: 'science',
    chapterNumber: 9,
    name: 'Light - Reflection and Refraction',
    description: 'Reflection, mirrors, refraction, lenses, optical instruments',
    topicCount: 6,
  },
  {
    id: 'sci-ch10',
    subjectId: 'science',
    chapterNumber: 10,
    name: 'The Human Eye and the Colourful World',
    description: 'Human eye, defects of vision, refraction through prisms, scattering of light',
    topicCount: 5,
  },
  {
    id: 'sci-ch11',
    subjectId: 'science',
    chapterNumber: 11,
    name: 'Electricity',
    description: 'Electric current, Ohms law, resistance, circuits, heating effect',
    topicCount: 6,
  },
  {
    id: 'sci-ch12',
    subjectId: 'science',
    chapterNumber: 12,
    name: 'Magnetic Effects of Electric Current',
    description: 'Magnetic field, electromagnetic induction, electric motors and generators',
    topicCount: 5,
  },
  {
    id: 'sci-ch13',
    subjectId: 'science',
    chapterNumber: 13,
    name: 'Our Environment',
    description: 'Ecosystems, food chains, waste management, ozone depletion',
    topicCount: 4,
  },
  {
    id: 'sci-ch14',
    subjectId: 'science',
    chapterNumber: 14,
    name: 'Sustainable Management of Natural Resources',
    description: 'Forest conservation, water management, coal and petroleum',
    topicCount: 4,
  },
];

export const scienceTopics: Record<string, Topic[]> = {
  'sci-ch1': [
    { id: 'sci-ch1-t1', chapterId: 'sci-ch1', name: 'Chemical Reactions — Definition and Characteristics', importance: 8, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch1-t2', chapterId: 'sci-ch1', name: 'Writing Chemical Equations', importance: 9, difficulty: 5, estimatedMinutes: 40 },
    { id: 'sci-ch1-t3', chapterId: 'sci-ch1', name: 'Types of Chemical Reactions', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch1-t4', chapterId: 'sci-ch1', name: 'Effects of Oxidation Reactions in Everyday Life', importance: 7, difficulty: 4, estimatedMinutes: 25 },
    { id: 'sci-ch1-t5', chapterId: 'sci-ch1', name: 'Balancing Chemical Equations', importance: 8, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch1-t6', chapterId: 'sci-ch1', name: 'Corrosion and Rancidity', importance: 6, difficulty: 3, estimatedMinutes: 20 },
  ],
  'sci-ch2': [
    { id: 'sci-ch2-t1', chapterId: 'sci-ch2', name: 'Acids and Bases — Properties', importance: 8, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch2-t2', chapterId: 'sci-ch2', name: 'Chemical Properties of Acids and Bases', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch2-t3', chapterId: 'sci-ch2', name: 'pH Scale and Its Importance', importance: 9, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'sci-ch2-t4', chapterId: 'sci-ch2', name: 'Salts — Definition and Types', importance: 7, difficulty: 5, estimatedMinutes: 30 },
    { id: 'sci-ch2-t5', chapterId: 'sci-ch2', name: 'Common Salt and Its Derivatives', importance: 6, difficulty: 4, estimatedMinutes: 25 },
    { id: 'sci-ch2-t6', chapterId: 'sci-ch2', name: 'Neutralization Reactions and Applications', importance: 8, difficulty: 5, estimatedMinutes: 35 },
  ],
  'sci-ch3': [
    { id: 'sci-ch3-t1', chapterId: 'sci-ch3', name: 'Physical Properties of Metals and Non-metals', importance: 7, difficulty: 3, estimatedMinutes: 25 },
    { id: 'sci-ch3-t2', chapterId: 'sci-ch3', name: 'Chemical Properties of Metals', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch3-t3', chapterId: 'sci-ch3', name: 'Reactively Series', importance: 9, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'sci-ch3-t4', chapterId: 'sci-ch3', name: 'Extraction of Metals', importance: 8, difficulty: 7, estimatedMinutes: 50 },
    { id: 'sci-ch3-t5', chapterId: 'sci-ch3', name: 'Alloys and Their Uses', importance: 6, difficulty: 4, estimatedMinutes: 20 },
    { id: 'sci-ch3-t6', chapterId: 'sci-ch3', name: 'Corrosion of Metals — Prevention', importance: 6, difficulty: 3, estimatedMinutes: 20 },
  ],
  'sci-ch4': [
    { id: 'sci-ch4-t1', chapterId: 'sci-ch4', name: 'Bonding in Carbon Compounds', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch4-t2', chapterId: 'sci-ch4', name: 'Versatile Nature of Carbon', importance: 8, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch4-t3', chapterId: 'sci-ch4', name: 'Homologous Series and Nomenclature', importance: 8, difficulty: 6, estimatedMinutes: 40, isHighYield: true },
    { id: 'sci-ch4-t4', chapterId: 'sci-ch4', name: 'Functional Groups', importance: 9, difficulty: 7, estimatedMinutes: 50, isHighYield: true },
    { id: 'sci-ch4-t5', chapterId: 'sci-ch4', name: 'Ethanol and Ethanoic Acid', importance: 7, difficulty: 5, estimatedMinutes: 30 },
    { id: 'sci-ch4-t6', chapterId: 'sci-ch4', name: 'Saponification and Soaps', importance: 5, difficulty: 3, estimatedMinutes: 20 },
  ],
  'sci-ch5': [
    { id: 'sci-ch5-t1', chapterId: 'sci-ch5', name: 'Modes of Nutrition — Autotrophic and Heterotrophic', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch5-t2', chapterId: 'sci-ch5', name: 'Respiration — Aerobic and Anaerobic', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch5-t3', chapterId: 'sci-ch5', name: 'Transportation in Human Beings', importance: 9, difficulty: 7, estimatedMinutes: 50, isHighYield: true },
    { id: 'sci-ch5-t4', chapterId: 'sci-ch5', name: 'Excretion in Human Beings', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch5-t5', chapterId: 'sci-ch5', name: 'Transportation in Plants', importance: 6, difficulty: 5, estimatedMinutes: 30 },
    { id: 'sci-ch5-t6', chapterId: 'sci-ch5', name: 'Nutrition — Diseases and Deficiencies', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'sci-ch6': [
    { id: 'sci-ch6-t1', chapterId: 'sci-ch6', name: 'Nervous System — Structure and Function', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch6-t2', chapterId: 'sci-ch6', name: 'Reflex Action and Reflex Arc', importance: 8, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch6-t3', chapterId: 'sci-ch6', name: 'Human Brain — Parts and Functions', importance: 8, difficulty: 6, estimatedMinutes: 40 },
    { id: 'sci-ch6-t4', chapterId: 'sci-ch6', name: 'Endocrine Glands and Hormones', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch6-t5', chapterId: 'sci-ch6', name: 'Coordination in Plants', importance: 5, difficulty: 3, estimatedMinutes: 20 },
  ],
  'sci-ch7': [
    { id: 'sci-ch7-t1', chapterId: 'sci-ch7', name: 'Modes of Reproduction — Asexual', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch7-t2', chapterId: 'sci-ch7', name: 'Sexual Reproduction in Plants', importance: 7, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch7-t3', chapterId: 'sci-ch7', name: 'Reproduction in Human Beings', importance: 8, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'sci-ch7-t4', chapterId: 'sci-ch7', name: 'Contraception Methods', importance: 6, difficulty: 4, estimatedMinutes: 25 },
    { id: 'sci-ch7-t5', chapterId: 'sci-ch7', name: 'Reproductive Health — STDs', importance: 5, difficulty: 3, estimatedMinutes: 20 },
  ],
  'sci-ch8': [
    { id: 'sci-ch8-t1', chapterId: 'sci-ch8', name: 'Heredity — Introduction and Rules', importance: 8, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch8-t2', chapterId: 'sci-ch8', name: 'Mendels Laws of Inheritance', importance: 9, difficulty: 7, estimatedMinutes: 50, isHighYield: true },
    { id: 'sci-ch8-t3', chapterId: 'sci-ch8', name: 'Sex Determination', importance: 7, difficulty: 4, estimatedMinutes: 25 },
    { id: 'sci-ch8-t4', chapterId: 'sci-ch8', name: 'Evolution — Evidence and Theories', importance: 6, difficulty: 5, estimatedMinutes: 30 },
    { id: 'sci-ch8-t5', chapterId: 'sci-ch8', name: 'Speciation and Natural Selection', importance: 5, difficulty: 4, estimatedMinutes: 25 },
  ],
  'sci-ch9': [
    { id: 'sci-ch9-t1', chapterId: 'sci-ch9', name: 'Reflection of Light — Laws and Mirror Formula', importance: 9, difficulty: 7, estimatedMinutes: 50, isHighYield: true },
    { id: 'sci-ch9-t2', chapterId: 'sci-ch9', name: 'Spherical Mirrors — Types and Image Formation', importance: 8, difficulty: 6, estimatedMinutes: 40 },
    { id: 'sci-ch9-t3', chapterId: 'sci-ch9', name: 'Refraction of Light — Laws and Snells Law', importance: 9, difficulty: 7, estimatedMinutes: 50, isHighYield: true },
    { id: 'sci-ch9-t4', chapterId: 'sci-ch9', name: 'Lenses — Types and Image Formation', importance: 8, difficulty: 6, estimatedMinutes: 40 },
    { id: 'sci-ch9-t5', chapterId: 'sci-ch9', name: 'Lens Formula and Magnification', importance: 8, difficulty: 7, estimatedMinutes: 45 },
    { id: 'sci-ch9-t6', chapterId: 'sci-ch9', name: 'Power of a Lens', importance: 7, difficulty: 5, estimatedMinutes: 25 },
  ],
  'sci-ch10': [
    { id: 'sci-ch10-t1', chapterId: 'sci-ch10', name: 'Structure of Human Eye', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch10-t2', chapterId: 'sci-ch10', name: 'Defects of Vision and Correction', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch10-t3', chapterId: 'sci-ch10', name: 'Refraction through a Prism', importance: 6, difficulty: 5, estimatedMinutes: 30 },
    { id: 'sci-ch10-t4', chapterId: 'sci-ch10', name: 'Scattering of Light', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch10-t5', chapterId: 'sci-ch10', name: 'Atmospheric Refraction and Phenomena', importance: 6, difficulty: 4, estimatedMinutes: 25 },
  ],
  'sci-ch11': [
    { id: 'sci-ch11-t1', chapterId: 'sci-ch11', name: 'Electric Current and Ohms Law', importance: 9, difficulty: 5, estimatedMinutes: 40, isHighYield: true },
    { id: 'sci-ch11-t2', chapterId: 'sci-ch11', name: 'Resistance — Factors and Combination', importance: 9, difficulty: 6, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch11-t3', chapterId: 'sci-ch11', name: 'Electric Circuits — Series and Parallel', importance: 8, difficulty: 6, estimatedMinutes: 40 },
    { id: 'sci-ch11-t4', chapterId: 'sci-ch11', name: 'Heating Effect of Electric Current', importance: 8, difficulty: 5, estimatedMinutes: 35, isHighYield: true },
    { id: 'sci-ch11-t5', chapterId: 'sci-ch11', name: 'Numerical Problems — Electricity', importance: 8, difficulty: 7, estimatedMinutes: 50 },
    { id: 'sci-ch11-t6', chapterId: 'sci-ch11', name: 'Household Electrical Circuits', importance: 5, difficulty: 4, estimatedMinutes: 20 },
  ],
  'sci-ch12': [
    { id: 'sci-ch12-t1', chapterId: 'sci-ch12', name: 'Magnetic Field and Field Lines', importance: 8, difficulty: 5, estimatedMinutes: 35 },
    { id: 'sci-ch12-t2', chapterId: 'sci-ch12', name: 'Force on a Current-Carrying Conductor', importance: 7, difficulty: 6, estimatedMinutes: 35 },
    { id: 'sci-ch12-t3', chapterId: 'sci-ch12', name: 'Electric Motor', importance: 8, difficulty: 6, estimatedMinutes: 40, isHighYield: true },
    { id: 'sci-ch12-t4', chapterId: 'sci-ch12', name: 'Electromagnetic Induction', importance: 9, difficulty: 7, estimatedMinutes: 45, isHighYield: true },
    { id: 'sci-ch12-t5', chapterId: 'sci-ch12', name: 'Electric Generator and Transformer', importance: 7, difficulty: 6, estimatedMinutes: 35 },
  ],
  'sci-ch13': [
    { id: 'sci-ch13-t1', chapterId: 'sci-ch13', name: 'Ecosystems — Components and Structure', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch13-t2', chapterId: 'sci-ch13', name: 'Food Chains and Food Webs', importance: 7, difficulty: 4, estimatedMinutes: 30 },
    { id: 'sci-ch13-t3', chapterId: 'sci-ch13', name: 'Environmental Problems — Pollution', importance: 6, difficulty: 3, estimatedMinutes: 25 },
    { id: 'sci-ch13-t4', chapterId: 'sci-ch13', name: 'Ozone Depletion and Waste Management', importance: 5, difficulty: 3, estimatedMinutes: 20 },
  ],
  'sci-ch14': [
    { id: 'sci-ch14-t1', chapterId: 'sci-ch14', name: 'Conservation of Forests and Wildlife', importance: 5, difficulty: 3, estimatedMinutes: 25 },
    { id: 'sci-ch14-t2', chapterId: 'sci-ch14', name: 'Water Management and Rainwater Harvesting', importance: 5, difficulty: 3, estimatedMinutes: 25 },
    { id: 'sci-ch14-t3', chapterId: 'sci-ch14', name: 'Coal and Petroleum — Conservation', importance: 5, difficulty: 3, estimatedMinutes: 20 },
    { id: 'sci-ch14-t4', chapterId: 'sci-ch14', name: 'Sustainable Development', importance: 4, difficulty: 2, estimatedMinutes: 15 },
  ],
};
